Repository openshift/cluster-policy-controller, pull requests merged in 2019-10, with the labels that each got.

#5 remove references to config related to legacy controllers
  pkg/cmd/cluster-policy-controller/openshiftcontrolplane_default.go
  pkg/cmd/cluster-policy-controller/policy_controller.go
  pkg/cmd/imageformat/imagetemplate.go
  pkg/cmd/imageformat/variable.go
  pkg/cmd/imageformat/variable_test.go
Labels: approved, lgtm, size/L

#6 make --config optional
  pkg/cmd/cluster-policy-controller/cmd.go
Labels: approved, lgtm, size/M

#8 update OWNERS, README, and Makefile `make images`
  Makefile
  OWNERS
  README.md
Labels: approved, lgtm, size/M

#9 allow --kubeconfig files
  pkg/cmd/cluster-policy-controller/cmd.go
Labels: approved, lgtm, size/XS

#13 generate self-signed certificates for serving the cluster-policy-cont…
  pkg/cmd/controller/net.go
Labels: approved, size/S

#14 LeaderElectionDefaulting to cluster-policy-controller
  pkg/cmd/cluster-policy-controller/openshiftcontrolplane_default.go
Labels: approved, lgtm, size/XS
